export const topics = [
  // Core Pixel identity and project
  "pixel art",
  "8-bit art",
  "generative art",
  "creative coding",
  "LNPixels",
  "collaborative canvas",
  "glitch art",
  "retrocomputing",
  "lofi aesthetics",
  "ASCII art",
  "demoscene",
  "glsl shaders",
  "p5.js",
  "three.js",
  "processing",
  "touchdesigner",
  "shader toy",
  "digital art",
  "art collaboration",
  "creative projects",
  "art communities",
  "visual art",
  "interactive art",
  "code art",
  "algorithmic art",

  // Bitcoin, Lightning, and sats culture
  "Bitcoin",
  "Lightning Network",
  "LNURL",
  "BOLT12",
  "zaps",
  "sats",
  "mempool fees",
  "self custody",
  "bitcoin ordinals",
  "on-chain art",
  "open source wallets",
  "lightning payments",
  "micropayments",
  "value4value",
  "bitcoin art",
  "btc",
  "satoshis",
  "lightning network",
  "wallet of satoshi",

  // Nostr ecosystem
  "Nostr",
  "nostr art",
  "nostr dev",
  "relays",
  "NIP-05",
  "NIP-57",
  "NIP-65",
  "note to zap",
  "nostr clients",
  "primal",
  "damus",
  "iris",
  "nostrudel",
  "nostr relay",
  "decentralized social",
  "censorship resistant",
  "nostr protocol",
  "nostr network",

  // Self-hosting survival vibes
  "self-hosted",
  "VPS",
  "homelab",
  "Docker",
  "Node.js",
  "TypeScript",
  "Postgres",
  "SQLite",
  "PM2",
  "reverse proxy",
  "nginx",
  "traefik",
  "tls certs",
  "monitoring",
  "uptime",
  "nakapay",
  "server down",
  "LNVPS.net",
  "locked in",
  "self-custody",
  "sovereignty",
  "sovereign individual",
  "sovereign identity",
  "indie web",
  "small web",
  "decentralization",
  
  // Nostr tags and social terms
  "#artstr",
  "#bitcoin",
  "#lightning",
  "#LN",
  "#btc", 
  "sats",
  "#nostr",
  "#mempool",
  "#bitcoinfees",
  "#crypto",
  "#blockchain",
  "#zap",
  "#plebchain",
  "#asknostr",
  "#memestr",
  "#memes",
  "#meme",
  "#technology",
  "#photography",
  "#jokes",
  '#asknostr',
  "#gm",
  "#primal",
  "#pleb",
  "#funny",
  "#grownostr",
  "#nostrart",
  "#zapathon",
  "#nostrplebs",

  // AI + agents (on-brand, broad reach)
  "AI art",
  "AI agents",
  "LLM",
  "prompting",
  "open source AI",
  "FOSS",
  "agent swarms",
  "tool use",
  "langchain",
  "autonomous agents",
  "machine learning",
  "artificial intelligence",
  "AI creativity",
  "AI collaboration",

  // Culture and engagement (still relevant to persona)
  "memes",
  "shitposting",
  "maker culture",
  "open source",
  "internet art",
  "webring",
  "digital minimalism",
  "creative commons",
  "collaboration",
  "community art",
  "online creativity",
  "digital culture",
  "internet culture",
  "creative expression",
  "artistic freedom",
    
  // Tech and development
  "programming",
  "coding",
  "software development",
  "web development",
  "javascript",
  "python",
  "rust",
  "golang",
  "typescript",
  "react",
  "svelte",
  "frontend",
  "backend",
  "fullstack",
  "api development",
  "web3",
  "decentralized apps",
    
  // Economics and freedom tech
  "freedom tech",
  "cypherpunk",
  "privacy",
  "encryption",
  "permissionless",
  "borderless money",
  "digital sovereignty",
  "financial freedom",
  "Austrian economics",
  "sound money",
  "inflation",
  "fiat",
  "central banks",
  "economic freedom",
];