/**
 * Character Definition (Legacy)
 * 
 * This file is kept for backwards compatibility but the preferred approach is:
 * 1. Use characterManifest from ./character/manifest.ts for pure data
 * 2. Use character.json generated by scripts/build-character.ts for CLI usage
 * 
 * The ElizaOS CLI resolves plugins by name string, avoiding ESM/CJS issues.
 */

import { type Character } from "@elizaos/core";
import { characterManifest } from "./character/manifest";

// Re-export the manifest as a Character with plugin names
// (plugins will be resolved by the CLI at runtime)
export const character: Character = {
  ...characterManifest,
  plugins: [
    '@elizaos/plugin-bootstrap',
    '@elizaos/adapter-postgres', 
    '@elizaos/plugin-sql',
    '@elizaos/plugin-openai',
    '@elizaos/plugin-openrouter',
    '@elizaos/plugin-telegram',
    '@elizaos/plugin-discord',
    '@elizaos/plugin-twitter',
    '@elizaos/plugin-knowledge',
    'pixel-plugin-nostr',
  ] as any,
};

export default character;

